/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AntdForm: typeof import('./../src/components/form/antd/antdForm.vue')['default']
    AntdFormExample: typeof import('./../src/components/form/antd/antdForm-example.vue')['default']
    BothTransAndAnimate: typeof import('./../src/components/vue/transition/bothTransAndAnimate.vue')['default']
    CardList: typeof import('./../src/components/common/cardList.vue')['default']
    CardList2: typeof import('./../src/components/common/cardList2.vue')['default']
    CardList3: typeof import('./../src/components/common/cardList3.vue')['default']
    copy: typeof import('./../src/components/form/element-plus/form copy.vue')['default']
    CssDrag: typeof import('./../src/components/other/cssDrag.vue')['default']
    DragColumn: typeof import('./../src/components/dragColumn.vue')['default']
    DragElement: typeof import('./../src/components/other/dragElement.vue')['default']
    DragSimple: typeof import('./../src/components/event/drag/dragSimple.vue')['default']
    DragUpload: typeof import('./../src/components/event/drag/dragUpload.vue')['default']
    DynamicHeight: typeof import('./../src/components/other/dynamicHeight.vue')['default']
    Form: typeof import('./../src/components/form/element-plus/form.vue')['default']
    'Form copy': typeof import('./../src/components/form/element-plus/form copy.vue')['default']
    FormExample: typeof import('./../src/components/form/element-plus/form-example.vue')['default']
    IntersectionObserver: typeof import('./../src/components/Api/intersectionObserver.vue')['default']
    Loading: typeof import('./../src/components/common/loading.vue')['default']
    ResizeObserver: typeof import('./../src/components/Api/resizeObserver.vue')['default']
    SchemaForm: typeof import('./../src/components/form/antd/schemaForm.vue')['default']
    Sortable: typeof import('./../src/components/plugins/sortable/sortable.vue')['default']
    SortableClasses: typeof import('./../src/components/plugins/sortable/sortableClasses.vue')['default']
    SortableDirective: typeof import('./../src/components/plugins/sortable/sortableDirective.vue')['default']
    SortableHandle: typeof import('./../src/components/plugins/sortable/sortableHandle.vue')['default']
    TransitionAnimate: typeof import('./../src/components/vue/transition/transitionAnimate.vue')['default']
    TransitionAniThird: typeof import('./../src/components/vue/transition/transitionAniThird.vue')['default']
    Vue3SeamlessScroll: typeof import('./../src/components/vue/Vue3SeamlessScroll.vue')['default']
    VueTransition: typeof import('./../src/components/vue/transition/vueTransition.vue')['default']
  }
}
